language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"  
  - "nightly"  
install:
  - pip install pytest
script:
  - python setup.py develop
  - pytest
notifications:
  email: false